version: '3'

services:
  db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root-passowrd
      MYSQL_DATABASE: agrismart
      MYSQL_USER: agrismart
      MYSQL_PASSWORD: agrismart
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: